### ISSUE TITLE
Credential.refreshIfNeeded fails on iOS

### ISSUE THREAD

**Issue by simplatek** [okta/okta-mobile-swift#101] opened 2022-11-09 23:26 UTC
### Describe the bug?

I am trying to refresh a token using the Credential.refreshIfNeeded API.  However, it always fails stating the request needs a client_id value.  I can see the client_id value is available in the configuration object or in the token.context.clientSettings,  however, I don't ever see it being used when building the APIRequest therefore it fails.   What am I doing wrong?  

![image](https://user-images.githubusercontent.com/2104397/200963230-ffae4dcd-92a7-4cee-9038-e3e6eaf5ad3b.png)

### What is expected to happen?

Refresh of token succeeds

### What is the actual behavior?

Refresh of token fails with OktaAPIError invalid_clientId, A client_id must be provided in the request.

### Reproduction Steps?

Sign in using the iOS SDK, Store the token using Credential.store.  Let token expire, try to refresh token using Credential.default?.refreshIfNeeded

### SDK Version(s)

OktaAuthFoundation (1.1.0)
OktaOAuth2 (1.1.0)
OktaWebAuthenticationUI (1.1.0)

### Build Information

Xcode 14

**Comment by mikenachbaur-okta** [comment] 2022-11-10 03:12
I'm curious @simplatek, what was the root cause of your issue? If there's some documentation updates, or simplification in the SDK, that might prevent your issue in the future, it would be nice to prevent developer friction in the future.

**Comment by simplatek** [comment] 2022-11-11 16:17
@daanvermeulen @mikenachbaur-okta Sorry I replied late, but the issue was an easy fix on my end.  The problem was the 'scopes' value must contain 'offline_access' in the Okta.plist configuration.  The reason is you will not get a refresh token if that value is not present.   

@mikenachbaur-okta I think one improvement to the SDK is provide a more clear error if we are missing 'offline_access' in the scope.  Something like invalid_refresh_token, 'Refresh token is required to perform a refresh' would been more helpful then 'A client_id must be provided in the request'.   

@daanvermeulen You will run into one more issue most likely if you continue refreshing a token, let it expire, prompt for okta credentials again, let token expire, refresh again...I noticed refreshIfNeeded will fail now with an `OAuth2ServerError.invalidGrant`.  This was fixed on my end also, by having to actually assign the default credential like this:

 `Credential.default = try Credential.store(token)`
 
I was thinking Credential.store call would update this value, however, that is not the case.  It is set one time and doesn't update to latest credential, so the refreshIfNeeded call pulls the refresh_token from the Credential.default and it is not the latest value therefore producing the error above.

**Comment by mikenachbaur-okta** [comment] 2022-11-14 19:43
I'm reopening this since there's additional discussion around the topic.

I've created a PR to improve error handling when a refresh token isn't present: https://github.com/okta/okta-mobile-swift/pull/102 if you or anyone else would like to review it.

**Comment by mikenachbaur-okta** [comment] 2022-11-14 19:51
@daanvermeulen 🤔 That's strange, when refreshing, even after the token has expired, the Credential Storage system should detect that the token has changed, and replace the underlying value in storage with the newly-serialized version.

Since you're having to explicitly assign a token to `Credential.default`, it's sounding to me like the previous credential isn't being removed.  AuthFoundation supports the use of multiple tokens (for example, you can have multiple users signed in simultaneously), so there might be invalid tokens still sitting in storage.

You can check out [this article on how to manage credentials](https://okta.github.io/okta-mobile-swift/development/authfoundation/documentation/authfoundation/managingusercredentials) which might clarify some things for you.

@daanvermeulen Please feel free to file a new issue for this specific problem, because it should "Just Work".

**Comment by simplatek** [comment] 2022-11-14 20:32
@mikenachbaur-okta thanks for updating the SDK.  i'm going to test the Credential.default issue more closely and let ya know what's going on.  I do call `try? Credential.default?.remove()` after I successfully sign-out on the Okta side.  I don't call that code anywhere else.   Does the previous credential need to be removed prior to store on my end or is this handled internally on the SDK side?

**Comment by mikenachbaur-okta** [comment] 2022-11-15 00:25
@simplatek Are you encountering situations where the user's session expires and you have to sign back in?

If you want to see what credentials are stored, you can enumerate through [Credential.allIDs](https://okta.github.io/okta-mobile-swift/development/authfoundation/documentation/authfoundation/credential/allids) to see if there are multiple credentials there.

A credential will automatically be removed when you sign out, or revoke, the token. Assigning to `default` won't necessarily remove an old credential, because the thought is that it can be used to switch between users in an app.

**Comment by daanvermeulen** [comment] 2022-12-01 14:50
Hi @mikenachbaur-okta ,
Thanks for updating the Okta library. I now get a different issue and let me describe the steps I take to get this issue.

I use the following code to log in and that succeeds:
`guard let issuerUrl = URL(string: appConfiguration.authOKTAIssuer), let redirectUrl = URL(string: appConfiguration.authOKTALoginRedirectUri) else { return }
    
    let auth = WebAuthentication(issuer: issuerUrl,
                                 clientId: appConfiguration.authOKTAClientId,
                                 scopes: appConfiguration.authOKTAScopes,
                                 redirectUri: redirectUrl,
                                 additionalParameters: nil)
    // Sign in using the above configuration
    auth.ephemeralSession = true
    let token = try await auth.signIn(from: nil)

    // Save the user's tokens
    Credential.default = try Credential.store(token)`

After this I force a refresh by using the following code:

`    if let credentialTest = Credential.default {
      credentialTest.refresh { result in
        switch result {
        case .failure(let error):
          self.errorLogger.send(event: .general(description: "Okta refresh token error: \(String(describing: error.errorDescription)), \(String(describing: error.failureReason)), recovery suggestion: \(String(describing: error.recoverySuggestion))", attributes: nil))
          refreshed(false)
        case .success:
          refreshed(true)
        }
      }
    }`

This fails and here is a screenshot I made:

<img width="461" alt="Screenshot 2022-12-01 at 15 46 40" src="https://user-images.githubusercontent.com/97460905/205083304-038ed243-3b56-4eee-bc15-6e763be85ec5.png">

I hope we can come to a fix of this issue. I migrated the old Okta framework to the new Okta Mobile and can't get this to work so far. The old framework with the same settings worked perfectly, also validation of the token.

Kind regards,

Daan Vermeulen

**Comment by mikenachbaur-okta** [comment] 2022-12-01 19:18
@daanvermeulen Can you share your list of scopes you have?

Also, can you tell me what the "Refresh token behaviour" is set to in your admin dashboard? e.g. go to Applications > [Your App] > General > Refresh Token and see if you have it set to "Rotate token after every use" or "Use persistent token"?

![Screen Shot 2022-12-01 at 11 18 23 AM](https://user-images.githubusercontent.com/74688448/205140554-fd17c379-98ea-4e2e-ad31-d278ef420f4e.png)

**Comment by daanvermeulen** [comment] 2022-12-01 19:27
@mikenachbaur-okta 

The scopes are as follow:
"scopes": "offline_access openid profile"

I asked the customer what their Okta refresh behavior is since we do not have access to their portal. Will get back to you next week on this. 

Thanks for the quick response and the help so far.

Daan

**Comment by koswedo** [comment] 2022-12-02 13:40
@daanvermeulen @mikenachbaur-okta 

Hi, I have the exact same error and the Refresh token behavior is set to "Use persistent token"

hope this help

**Comment by daanvermeulen** [comment] 2022-12-06 12:01
Alright so I got back info from the client and they say that refreshing is disabled on their side. I guess that does fix the issue that was originally posted and fixed here because it should work correctly if the client turns this on.

What I am still curious about, when using the old Okta framework I used the 'introspect' method and if that said the token was not 'active' then I called the 'renew' method. Now on Okta Mobile there I could no longer find this renew method. Is there an alternative for this?

**Comment by koswedo** [comment] 2022-12-06 16:11
I have looked into the code in this repository and there is something I don't quite understand.
In `OAuthClient`, the [refresh ](https://github.com/okta/okta-mobile-swift/blob/ff25cfb68fa8f6034fdb02d57c1af6d39996f171/Sources/AuthFoundation/OAuth2/OAuth2Client.swift#L202) function, it tests for the `refreshToken.rawValue` in `clientSettings`, and Indeed, the refresh token is not there. It is in `token` passed in parameters though.

Have I missed something so the refresh token would be also in `clientSettings`?

Thank you for your help

**Comment by simplatek** [comment] 2022-12-06 18:14
> Alright so I got back info from the client and they say that refreshing is disabled on their side. I guess that does fix the issue that was originally posted and fixed here because it should work correctly if the client turns this on.
> 
> What I am still curious about, when using the old Okta framework I used the 'introspect' method and if that said the token was not 'active' then I called the 'renew' method. Now on Okta Mobile there I could no longer find this renew method. Is there an alternative for this?

You can use the Credential.refreshIfNeeded function to renew the access token.

**Comment by daanvermeulen** [comment] 2022-12-06 21:35
The thing is @simplatek , if I use the refreshIfNeeded, I get logged out after a day or less, does that mean the access token expired and it cannot refresh because there is no refresh token available? It is not a very good user experience. When using the old way with introspect+renew in OktaOidc I was hardly ever logged out so there is surely a difference.

**Comment by mikenachbaur-okta** [comment] 2022-12-06 22:14
@koswedo Don't worry, I re-opened this bug a few weeks ago because I wanted to get more information about this issue, and wanted to get to the bottom of it. I've never seen this situation in any of my testing, but that doesn't mean that the problem doesn't exist. I'm hopeful that I can figure out what the root cause is, so I can fix it in a TDD fashion.

@daanvermeulen The new SDK has an [introspect](https://okta.github.io/okta-mobile-swift/development/authfoundation/documentation/authfoundation/credential/introspect(_:completion:)) function, which you can still use to check the validity of a token.

I have a few theories as to what the problem might be, but since I haven't been able to reproduce it, I don't want to try pushing changes in the hopes that the problem goes away. So perhaps you all can help me.

I have two current theories:

## Token client settings

First, since AuthFoundation is intended to be generic, supporting different authentication flows and authorization servers (not just Okta), the values required by the Token endpoint for refreshing a token can vary. As a result, the `Token` class has a `Context` struct that defines the configuration and "client settings" necessary to trigger a refresh. This way, a token can continue to be refreshed, even if the client configuration may have changed.

The `clientSettings` property contains information such as the client ID, scopes, and redirect URI necessary by the authorization server to trigger a refresh. This allows the Token to be refreshed independent of the client that was used to create it.

If there's some authorization server configuration that requires additional information to successfully refresh a token which isn't being stored in that object, this could potentially lead to a refresh failing.

## Token storage replacement

The new SDK aims to support the storage of multiple credentials simultaneously for more complex use-cases. Since Okta uses JWTs as an access token, and refresh tokens can be rotated, there's no concrete identifier that can be used to semantically compare tokens. As a result, the SDK assigns a unique UUID to a credential when it's first stored. When a token is refreshed, since we know the new token represents the same credential as the one being refreshed, we utilize custom `CodingUserInfoKey` values to pass the previous UUID to the new token, so when it's stored, the token represents the same logic credential. This allows the keychain [TokenStorage](https://okta.github.io/okta-mobile-swift/development/authfoundation/documentation/authfoundation/tokenstorage) implementation to trigger a `replace`, instead of an `add` operation.

There's a possibility that this mechanism may be failing. For example, the refresh may succeed, but the new token may not be stored for some reason.

One way to test for this is to check the [Credential.allIDs](https://okta.github.io/okta-mobile-swift/development/authfoundation/documentation/authfoundation/credential/allids) property to see if a refresh is inadvertently creating new tokens for the refreshed value.

## Summary

If anyone is able to solidly reproduce this, I would love to get more information. If you can set a debugger breakpoint to help narrow the problem down, or can help me to reproduce the problem locally, I would be very grateful.

**Comment by mikenachbaur-okta** [comment] 2022-12-07 19:23
Thank you for your help everyone! I believe I tracked down the root cause, and have PR #106 open to fix the issue.  If anyone would like to try this out to verify the fix works on your end, I'll get this released ASAP.

**Comment by mikenachbaur-okta** [comment] 2022-12-08 03:14
@daanvermeulen @simplatek @koswedo I just released version 1.1.3 which includes this fix, and hopefully addresses this issue. Please let me know if this fixes your issue.

**Comment by simplatek** [comment] 2022-12-09 00:44
@mikenachbaur-okta Thanks for pushing out another fix.  I will try to validate it also after I get some other things out of the way.  Meanwhile, I'm not sure where to post this question after searching the web for an answer, thought you might now off-hand.   I'm using SSO, redirect model with this iOS SDK.  When we sign-out, we always get redirected to perform this sign-out which is understandable.  However, I'm looking for a way to sign-out without this redirect.  Not just revoking the access/refresh token but also clearing the okta session (shared cookies) in the local browser so we ensure the user signed out fully and must re-enter credentials to sign again.  This use case entails a user signs into our app with Okta, but then un-installs the app.  We need a way to ensure they are signed out of Okta fully so when a fresh install occurs they go thru the standard sign-in flow with credentials required again.   Is there a way to some how clear the cached cookies associated with a given Okta session without redirecting to browser for this?

**Comment by daanvermeulen** [comment] 2022-12-09 09:51
@simplatek please check the code I shared above, it has the 'auth.ephemeralSession = true' which means that no cookies will be stored, if you have this enabled and logout, you have to enter your credentials over again.


@mikenachbaur-okta I just tested 1.1.2 and tested the 'refresh' method. It returned failing. Then I updated to 1.1.3 and ran the refresh and it returned 'succeeded'. So I guess this is good? Because the client enabled the refresh token now on their end.

**Comment by Sushree-nayak-2022** [comment] 2022-12-09 15:17
Hi @mikenachbaur-okta - Can you please update https://github.com/okta/okta-idx-swift sdk  as well  which internally uses https://github.com/okta/okta-mobile-swift ?

**Comment by simplatek** [comment] 2022-12-09 17:12
> @simplatek please check the code I shared above, it has the 'auth.ephemeralSession = true' which means that no cookies will be stored, if you have this enabled and logout, you have to enter your credentials over again.
> 
> @mikenachbaur-okta I just tested 1.1.2 and tested the 'refresh' method. It returned failing. Then I updated to 1.1.3 and ran the refresh and it returned 'succeeded'. So I guess this is good? Because the client enabled the refresh token now on their end.

@daanvermeulen thanks for pointing out the ephemeralSession flag.  I did try that before and while it essential resolves the issue, I'm not 100% sure if it is acceptable in our situation.  We are using Okta for SSO, so I believe if we aren't storing the credentials in the shared cookies, it essentially disables SSO.  I will have to ask our product managers if they are ok with this behavior.  I was looking for a local/server API to clear the shared cookies for a particular okta session, so far haven't found it.  Thanks again.

**Comment by Sushree-nayak-2022** [comment] 2022-12-09 20:06
Hi @mikenachbaur-okta - I tested this sdk version 1.1.3 .. the issue is not fixed yet I believe. If the access token expired and refresh token is still valid this function  **private func performRefresh(token: Token, clientSettings: [String: String])** returns failure message saying   ▿ failure : APIClientError
    ▿ serverError : OAuth2ServerError
      - code : AuthFoundation.OAuth2ServerError.Code.invalidGrant
      ▿ description : Optional<String>
        - some : "The refresh token is invalid or expired."
        - 
@daanvermeulen - you mentioned its working for you...are you getting new access token ?

**Comment by mikenachbaur-okta** [comment] 2022-12-09 20:13
@Sushree-nayak-2022 The refresh token itself can expire, which means the access token can't be refreshed. It's usually a good practice to set a short access token expiration duration, and a longer refresh token duration.  If the app continues to refresh, the session can be kept alive.

**Comment by Sushree-nayak-2022** [comment] 2022-12-09 20:31
@mikenachbaur-okta ---That's totally correct. What I am saying is access token is not getting refreshed successfully using valid refresh token on SDK 1.1.3  Credential.refreshIfNeeded  is still failing even though I have valid refresh token and access token expired.. 
Credential.refreshIfNeeded should refresh my access token right?

**Comment by Sushree-nayak-2022** [comment] 2022-12-11 04:16
Hi @mikenachbaur-okta - I was reading your previous comments and was doing some more re I  believe among your 2 theory the issue is in Token storage replacement as you mentioned below . The refresh works fine  and Credential.default also gets updated if my app is still running and I am calling refresh function. If I kill the app and reopen Credential.default  fetches the old refresh token.

Token storage replacement
The new SDK aims to support the storage of multiple credentials simultaneously for more complex use-cases. Since Okta uses JWTs as an access token, and refresh tokens can be rotated, there's no concrete identifier that can be used to semantically compare tokens. As a result, the SDK assigns a unique UUID to a credential when it's first stored. When a token is refreshed, since we know the new token represents the same credential as the one being refreshed, we utilize custom CodingUserInfoKey values to pass the previous UUID to the new token, so when it's stored, the token represents the same logic credential. This allows the keychain [TokenStorage](https://okta.github.io/okta-mobile-swift/development/authfoundation/documentation/authfoundation/tokenstorage) implementation to trigger a replace, instead of an add operation.

There's a possibility that this mechanism may be failing. For example, the refresh may succeed, but the new token may not be stored for some reason.

One way to test for this is to check the [Credential.allIDs](https://okta.github.io/okta-mobile-swift/development/authfoundation/documentation/authfoundation/credential/allids) property to see if a refresh is inadvertently creating new tokens for the refreshed value.

**Comment by simplatek** [comment] 2022-12-12 17:48
> https://developer.okta.com/docs/reference/api/oidc/#parameter-details

@mikenachbaur-okta Thank you for the links you gave me, this is very helpful information.

**Comment by mikenachbaur-okta** [comment] 2022-12-20 23:49
@Sushree-nayak-2022 I believe the issue you're facing is being tracked by issue #100, and I have a PR and a release that fixes that issue.

@simplatek @daanvermeulen I think this issue was fixed in the recent release, so I'm going to close this issue. If you have further problems, please feel free to log an additional ticket.

Furthermore, if any of you have feature requests, please don't hesitate to log a separate issue for it. Our goal is to improve your developer experience, and if there's something we're missing, please let us know!

**Closed by mikenachbaur-okta** 2022-12-20 23:49 UTC
Labels: bug
