### ISSUE TITLE
Web sign in page doesn't fit screen

### ISSUE THREAD

**Issue by aetherealtech** [okta/okta-mobile-swift#83] opened 2022-07-12 14:10 UTC
### Describe the bug?

When using `WebAuthentication`, the browser sign in page that gets opened has content larger than the device screen (in both dimensions), and it is scrollable.

### What is expected to happen?

The sign in page content should fit the screen and not be scrollable.

### What is the actual behavior?

The sign in page content is larger than the screen and is scrollable.

### Reproduction Steps?

Open the WebSignIn (iOS) sample (after providing config) on an iPhone 13 Pro simulator and click "Sign In"

### SDK Version(s)

1.0.0

**Comment by emmanuelogunmuyiwa-okta** [comment] 2022-07-12 16:46
Thanks for reporting the issue @aetherealtech.  I was able to reproduce the issue and it seems to be caused by the device page zoom setting. At 100%, the content becomes scrollable. The page zoom setting is within the html of the sign-in-page on the developer portal and can be adjusted there.

**Comment by aetherealtech** [comment] 2022-07-15 12:20
@emmanuelogunmuyiwa-okta Thanks for you quick response!  So do you recommend customizing the login page HTML to address this?

I've had this problem with web content on mobile devices before.  If we go this route I can share the HTML header attributes that we use to force content on mobile to fit the screen and not scroll.

**Comment by emmanuelogunmuyiwa-okta** [comment] 2022-07-15 14:41
@aetherealtech You can customize your minimum or maximum scale factors to best suit your use case. Please have a look at the [developer documentation](https://developer.okta.com/docs/guides/custom-widget/main/) as well, it provides you further explanations on how to customize the Sign-In Widget.

**Comment by emmanuelogunmuyiwa-okta** [comment] 2022-07-17 18:41
Thank you for the question @aetherealtech, I hope the answers helped.  I'm going to close this, feel free to re-open if needed (or ask new questions in new issues).

**Closed by emmanuelogunmuyiwa-okta** 2022-07-17 18:41 UTC
Labels: bug
